### ISSUE TITLE
broken requirements

### ISSUE THREAD

**Issue by bukowa** [praekelt/swagger-django-generator#22]
````python
Running command git clone -q https://github.com/praekelt/swagger-parser /app/src/swagger-parser
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/app/src/swagger-parser/setup.py'"'"'; __file__='"'"'/app/src/swagger-parser/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"
');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /app/src/swagger-parser/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/app/src/swagger-parser/setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

````
I know there's a fix in other issue, but its a workaround.

**Comment by SellamiRami** [comment]
Hello @bukowa 
I'm facing the same issue as you. Could you please tell whether you find a solution for that?
Thank you in advance for your response.
Have a nice day,
Rami.

**Comment by bukowa** [comment]
> Hello @bukowa I'm facing the same issue as you. Could you please tell whether you find a solution for that? Thank you in advance for your response. Have a nice day, Rami.

Sorry I no longer remember ^^
