### ISSUE TITLE
make virtualenv results in "ModuleNotFoundError: No module named 'pip.req'"

### ISSUE THREAD

**Issue by kylemantesso** [praekelt/swagger-django-generator#28]
Any idea why I get this error when i run `make virtualenv`?

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/kylemantesso/dev/swagger-django-generator/ve/src/swagger-parser/setup.py", line 4, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
```

**Comment by SellamiRami** [comment]
Hello @kylemantesso 
I'm facing the same issue as you. Could you please tell whether you find a solution for that?
Thank you in advance for your response. 
Have a nice day, 
Rami.

**Comment by cobusc** [comment]
@SellamiRami can you try replacing the following line in `requirements.txt`
```
-e git+https://github.com/praekelt/swagger-parser@master#egg=swagger-parser
```
with
```
swagger-parser
```
Hopefully the upstream package have been updated and the fork is not necessary anymore. Please create PR if it works.
